name: Auto Minify Commit Message

on:
  push:
    branches:
      - main

jobs:
  minify_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4

      - name: Configurer Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Obtenir le message de commit et le minifier
        id: minify
        run: |
          original=$(git log -1 --pretty=%B)
          cleaned=$(echo "$original" | tr '\n' ' ' | sed -E 's/\s+/ /g' | sed -E 's/\s*([.,!?;:])\s*/\1/g' | sed -E 's/^\s+|\s+$//g')
          echo "Minified message: $cleaned"
          echo "minified_message=$cleaned" >> $GITHUB_OUTPUT

      - name: Faire un commit avec le message minifié
        run: |
          echo "# Commit minifié par workflow" > minify.txt
          git add minify.txt
          git commit -m "${{ steps.minify.outputs.minified_message }}"
          git push